export const data = [
  {
    id: 1,
    companyName: "Linear company",
    jobTitle: "Software Engineer",
    companyLogo: "job-1.png",
    minPrice: "20",
    maxPrice: "30",
    jobLocation: "Brussels",
    postingDate: "2023-11-03",
    experienceLevel: "Any experience",
    employmentType: "Full-time",
    description:
      "A leading tech firm specializing in AI and cloud computing, helping businesses scale with innovative software solutions.",
  },
  {
    id: 2,
    companyName: "Notion",
    jobTitle: "Web Developer",
    companyLogo: "job-2.png",
    minPrice: "40",
    maxPrice: "50",
    jobLocation: "San Francisco",
    postingDate: "2023-11-02",
    experienceLevel: "Internship",
    employmentType: "Temporary",
    description:
      "A renewable energy company committed to sustainable power solutions, including solar, wind, and hydroelectric innovations.",
  },
  {
    id: 3,
    companyName: "Spline studio",
    jobTitle: "Data Scientist",
    companyLogo: "job-3.png",
    minPrice: "40",
    maxPrice: "50",
    jobLocation: "Seattle",
    postingDate: "2023-10-28",
    experienceLevel: "Any experience",
    employmentType: "Full-time",
    description:
      "A software development company that builds high-performance web and mobile applications for startups and enterprises.",
  },
  {
    id: 4,
    companyName: "Raycast corp",
    jobTitle: "UI/UX Designer",
    companyLogo: "job-4.png",
    minPrice: "40",
    maxPrice: "50",
    jobLocation: "London",
    postingDate: "2023-10-05",
    experienceLevel: "Work remotely",
    employmentType: "Part-time",
    description:
      "A trusted financial institution offering modern banking solutions, investment opportunities, and secure digital transactions.",
  },
  {
    id: 5,
    companyName: "Loom",
    jobTitle: "Frontend Developer",
    companyLogo: "job-5.png",
    minPrice: "50",
    maxPrice: "75",
    jobLocation: "London",
    postingDate: "2023-10-28",
    experienceLevel: "Intership",
    employmentType: "Full-time",
    description:
      "An EdTech company providing online courses, interactive learning tools, and AI-powered tutoring systems.",
  },
  {
    id: 6,
    companyName: "Trainline group",
    jobTitle: "DevOps Engineer",
    companyLogo: "job-6.png",
    minPrice: "80",
    maxPrice: "120",
    jobLocation: "Boston",
    postingDate: "2023-10-05",
    experienceLevel: "Intership",
    employmentType: "Temporary",
    description:
      "A biotech company dedicated to developing cutting-edge medicines and healthcare solutions for a healthier world.",
  },

  {
    id: 7,
    companyName: "Yata",
    jobTitle: "Developer III",
    companyLogo: "job-7.jpeg",
    minPrice: 30,
    maxPrice: 25,
    jobLocation: "Jinanten",
    postingDate: "2024-05-17",
    exprienceLevel: "Work Remotely",
    employmentType: "Full-time",
    description:
      "An automotive engineering company revolutionizing self-driving technology and electric vehicle advancements.",
  },
  {
    id: 8,
    companyName: "Rhycero",
    jobTitle: "Social Worker",
    companyLogo: "job-8.jpeg",
    minPrice: 26,
    maxPrice: 89,
    jobLocation: "Santo Niño",
    postingDate: "2024-05-05",
    exprienceLevel: "Internship",
    employmentType: "temporary",
    description:
      "Protecting businesses with state-of-the-art cybersecurity solutions, including data encryption and threat detection.",
  },
  {
    id: 9,
    companyName: "Zoomcast",
    jobTitle: "Professor",
    companyLogo: "job-9.jpeg",
    minPrice: 20,
    maxPrice: 91,
    jobLocation: "Sawaengha",
    postingDate: "2024-07-02",
    exprienceLevel: "Work Remotely",
    employmentType: "Full-time",
    description:
      "A telecom giant providing high-speed internet, mobile networks, and cloud-based communication services.",
  },
  {
    id: 10,
    companyName: "Twitterwire",
    jobTitle: "Research Nurse",
    companyLogo: "job-10.jpeg",
    minPrice: 29,
    maxPrice: 40,
    jobLocation: "Zahlé",
    postingDate: "2025-02-25",
    exprienceLevel: "Any Experience",
    employmentType: "temporary",
    description:
      "An innovative robotics company designing AI-powered robots for industries like healthcare, manufacturing, and logistics.",
  },
  {
    id: 11,
    companyName: "Youfeed",
    jobTitle: "Human Resources Manager",
    companyLogo: "job-11.jpeg",
    minPrice: 9,
    maxPrice: 6,
    jobLocation: "Kambingan",
    postingDate: "2024-04-12",
    exprienceLevel: "Work Remotely",
    employmentType: "Full-time",
    description:
      "A telecom giant providing high-speed internet, mobile networks, and cloud-based communication services.",
  },
  {
    id: 12,
    companyName: "Roombo",
    jobTitle: "VP Accounting",
    companyLogo: "job-12.jpeg",
    minPrice: 28,
    maxPrice: 35,
    jobLocation: "Nigeria",
    postingDate: "2025-02-21",
    exprienceLevel: "Internship",
    employmentType: "temporary",
    description:
      "A construction company specializing in smart cities, eco-friendly buildings, and modern infrastructure projects.",
  },
  {
    id: 13,
    companyName: "Demizz",
    jobTitle: "Desktop Support Technician",
    companyLogo: "job-13.jpeg",
    minPrice: 62,
    maxPrice: 86,
    jobLocation: "New York",
    postingDate: "2025-01-16",
    exprienceLevel: "Work Remotely",
    employmentType: "Full-time",
    description:
      "A construction company specializing in smart cities, eco-friendly buildings, and modern infrastructure projects.",
  },
  {
    id: 14,
    companyName: "Ailane",
    jobTitle: "Financial Analyst",
    companyLogo: "job-14.jpeg",
    minPrice: 20,
    maxPrice: 98,
    jobLocation: "Jacaltenango",
    postingDate: "2024-18-6",
    exprienceLevel: "Internship",
    employmentType: "Full-time",
    description:
      "A biotechnology firm focused on genetic research, personalized medicine, and innovative healthcare treatments.",
  },
  {
    id: 15,
    companyName: "BioGenix",
    jobTitle: "Analyst Programmer",
    companyLogo: "job-15.jpeg",
    minPrice: 75,
    maxPrice: 30,
    jobLocation: "Lagos",
    postingDate: "2024-29-7",
    exprienceLevel: "Internship",
    employmentType: "Full-time",
    description:
      "A biotechnology firm focused on genetic research, personalized medicine, and innovative healthcare treatments.",
  },
  {
    id: 16,
    companyName: "Devpoint",
    jobTitle: "Accounting Assistant III",
    companyLogo: "job-16.jpeg",
    minPrice: 41,
    maxPrice: 88,
    jobLocation: "Atlanta",
    postingDate: "2024-17-7",
    exprienceLevel: "Any Experience",
    employmentType: "Full-time",
    description:
      "A gaming company creating immersive video games, AR/VR experiences, and multiplayer online worlds.",
  },
  {
    id: 17,
    companyName: "Brightbean",
    jobTitle: "Compensation Analyst",
    companyLogo: "job-17.jpeg",
    minPrice: 98,
    maxPrice: 83,
    jobLocation: "Orland",
    postingDate: "2024-5-4",
    exprienceLevel: "Any Experience",
    employmentType: "temporary",
    description:
      "A supply chain and logistics company optimizing global transportation and delivery networks.",
  },
  {
    id: 18,
    companyName: "Zoomdog",
    jobTitle: "Actuary",
    companyLogo: "job-18.jpeg",
    minPrice: 70,
    maxPrice: 87,
    jobLocation: "Paris",
    postingDate: "2024-15-6",
    exprienceLevel: "Internship",
    employmentType: "temporary",
    description: "Immobilization of Face using Other Device",
  },
  {
    id: 19,
    companyName: "Linkbridge",
    jobTitle: "Editor",
    companyLogo: "job-19.jpeg",
    minPrice: 61,
    maxPrice: 80,
    jobLocation: "North",
    postingDate: "2024-7-12",
    exprienceLevel: "Any Experience",
    employmentType: "Full-time",
    description:
      "A venture capital firm investing in promising startups, driving innovation and supporting entrepreneurial growth.",
  },
  {
    id: 20,
    companyName: "Meembee",
    jobTitle: "Environmental Specialist",
    companyLogo: "job-20.jpeg",
    minPrice: 92,
    maxPrice: 53,
    jobLocation: "Canada",
    postingDate: "2024-20-10",
    exprienceLevel: "Work Remotely",
    employmentType: "Full-time",
    description:
      "A travel and tourism company offering luxury vacations, corporate travel planning, and exclusive destination packages.",
  },
];
